# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\ridp.messaging\"\xd0\x01\n\x0fMessageEnvelope\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12<\n\x07payload\x18\x02 \x03(\x0b\x32+.idp.messaging.MessageEnvelope.PayloadEntry\x12\x13\n\x0boccurred_at\x18\x03 \x01(\t\x12\x0e\n\x06source\x18\x04 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x05 \x01(\t\x1a.\n\x0cPayloadEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEENVELOPE_PAYLOADENTRY']._loaded_options = None
  _globals['_MESSAGEENVELOPE_PAYLOADENTRY']._serialized_options = b'8\001'
  _globals['_MESSAGEENVELOPE']._serialized_start=33
  _globals['_MESSAGEENVELOPE']._serialized_end=241
  _globals['_MESSAGEENVELOPE_PAYLOADENTRY']._serialized_start=195
  _globals['_MESSAGEENVELOPE_PAYLOADENTRY']._serialized_end=241
# @@protoc_insertion_point(module_scope)
