from typing import Protocol
from loms.contexts.shipment.domain.model.shipment import Shipment
from loms.contexts.shipment.domain.vo.ids import TenantId, ShipmentId

class ShipmentRepository(Protocol):
    async def get(self, tenant_id: TenantId, shipment_id: ShipmentId) -> Shipment | None: ...
    async def save(self, shipment: Shipment) -> None: ...

class IdempotencyRepository(Protocol):
    async def get(self, tenant_id: str, key: str, method: str, path: str): ...
    async def upsert(self, *, tenant_id: str, key: str, method: str, path: str, request_hash: str, status_code: int, response_body: dict): ...

class OutboxRepository(Protocol):
    async def append(self, *, tenant_id: str, aggregate_type: str, aggregate_id: str, aggregate_version: int, event_type: str, event_version: int, payload: dict, headers: dict | None = None): ...
