from typing import Protocol, AsyncContextManager

class UnitOfWork(Protocol):
    async def __aenter__(self) -> "UnitOfWork": ...
    async def __aexit__(self, exc_type, exc, tb) -> None: ...

    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...

    # repositories
    @property
    def shipments(self): ...
    @property
    def idempotency(self): ...
    @property
    def outbox(self): ...
