from typing import Any, Dict, Generic, List, Optional, Protocol, TypeVar

from idp.framework.infrastructure.persistence.specification.core.base import (
    Specification,
)
from idp.framework.infrastructure.persistence.specification.core.type import Page, PageParams

PO = TypeVar('PO')
ID = TypeVar('ID')


class RepositoryDelegate(Protocol, Generic[PO, ID]):
    """
    与 BaseRepository 实现对齐的持久化委托协议。
    """
    async def get_po_by_id(self, id: ID) -> Optional[PO]:
        """按主键获取 PO"""
        ...
        
    async def query_po_by_spec(self, spec: Specification[PO]) -> List[PO]: ...

    async def query_one_po_by_spec(
        self, spec: Specification[PO]) -> Optional[PO]: ...

    async def query_all_po_by_spec(
        self, spec: Specification[PO]) -> List[PO]: ...

    async def count_po_by_spec(self, spec: Specification[PO]) -> int: ...
    async def exists_po_by_spec(self, spec: Specification[PO]) -> bool: ...
    async def query_po_page_by_spec(
        self, spec: Specification[PO], page_params: PageParams) -> Page[PO]: ...

    async def create_po(self, entity: PO) -> PO: ...
    async def update_po(self, entity: PO) -> PO: ...
    async def delete_po(self, entity: PO) -> None: ...
    async def batch_po_create(self, entities: List[PO]) -> List[PO]: ...
    async def batch_po_update(self, entities: List[PO]) -> List[PO]: ...
    async def batch_po_delete(self, entities: List[PO]) -> None: ...

    
