from collections.abc import Iterable
from typing import Protocol


class Outbox(Protocol):
    async def add(self, topic: str, payload: dict) -> None: ...
    async def pull_batch(self, limit: int = 100) -> Iterable[dict]: ...
    async def mark_published(self, id: str) -> None: ...
